### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by matejvelikonja** [Gutza/octave-daemon#11]
Can you please create a new release, for example 1.1.0 or something?

**Comment by Gutza** [comment]
Why? There are no changes, functional or otherwise. It's the same code base, just packaged differently.

**Comment by matejvelikonja** [comment]
There are new functionalities, not code base, but the way how the library is installed. So I can just easily type in composer.json version and everything is installed.

And also one pull request before, I've fixed static accessors issue, so that was actually a bug fix.

**Comment by Gutza** [comment]
Fair enough, I created v1.0.2.
